pwd_fold_1: /home/gigabot/shared/AT_Python_Linux/HW_3/dir_file
pwd_fold_2: /home/gigabot/shared/AT_Python_Linux/HW_3/dir_zip
pwd_fold_3: /home/gigabot/shared/AT_Python_Linux/HW_3/dir_unzip
pwd_4: /proc/loadavg
pwd_stat: /home/gigabot/shared/AT_Python_Linux/HW_3/stat.txt
count: 3
